name: pigmento
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  lottie: ^3.1.2
  audioplayers: ^6.8.1
  vibration: ^3.2.0
  flutter_secure_storage: ^10.3.1

  # Suite de Firebase con versiones totalmente armonizadas
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.3
  firebase_crashlytics: ^4.3.3
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/icon1.png
    - assets/imagenes/icon2.png
    - assets/imagenes/fondo.jpeg
    - assets/imagenes/sello.png
    - assets/spinners/spinner.json
    - assets/spinners/bool.json 
    - assets/avatar/
    - assets/audio/
    - assets/imagenes/mapa.png
    - assets/imagenes/fondo.jpeg
    - assets/imagenes/segundo.jpeg
    - assets/imagenes/fondo_barra.png
    - assets/imagenes/header.png
    - assets/imagenes/barra.png
    - assets/imagenes/corazon.png
    - assets/imagenes/horno.png
    - assets/imagenes/cristal.png
    - assets/imagenes/baja.png
    - assets/imagenes/fichados.png
    - assets/imagenes/tarjeta.png
    - assets/imagenes/opciones.png
    - assets/imagenes/fondoagua.jpeg
    - assets/imagenes/ficha.png
    - assets/imagenes/opcion.png
    - assets/imagenes/cañon.png
    - assets/imagenes/cofre.png
    - assets/imagenes/cuerda.png
    - assets/imagenes/brujula.png
    - assets/imagenes/rueda.png
    - assets/imagenes/fondobarco.png
    - assets/imagenes/cajasol.png
    - assets/imagenes/cajafria.png
    - assets/imagenes/tabla.png
    - assets/imagenes/cofres.png
    - assets/imagenes/mastil.png
    - assets/imagenes/lingote_amarillo.png
    - assets/imagenes/lingote_naranja.png
    - assets/imagenes/polvo_azul.png
    - assets/imagenes/polvo_turquesa.png
    - assets/imagenes/pantallajuego.jpeg