// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWRDYEVXovVqFoKtNy3k9e9nuuRMkkAM',
    appId: '1:189818621892:web:dad9a0aa6d2f90630a9e91',
    messagingSenderId: '189818621892',
    projectId: 'pigmento-4fa57',
    authDomain: 'pigmento-4fa57.firebaseapp.com',
    storageBucket: 'pigmento-4fa57.firebasestorage.app',
    measurementId: 'G-GHF5P2XWS3',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYDo1x9wvvB69upGYLkO3_15ya7xdnZU',
    appId: '1:189818621892:android:85e4371b4b75287b0a9e91',
    messagingSenderId: '189818621892',
    projectId: 'pigmento-4fa57',
    storageBucket: 'pigmento-4fa57.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwB_1VJso9cEcokr5mEG7Qz51ydGVA2zw',
    appId: '1:189818621892:ios:cdaf7dc013bf1ea70a9e91',
    messagingSenderId: '189818621892',
    projectId: 'pigmento-4fa57',
    storageBucket: 'pigmento-4fa57.firebasestorage.app',
    iosBundleId: 'com.example.pigmento',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwB_1VJso9cEcokr5mEG7Qz51ydGVA2zw',
    appId: '1:189818621892:ios:cdaf7dc013bf1ea70a9e91',
    messagingSenderId: '189818621892',
    projectId: 'pigmento-4fa57',
    storageBucket: 'pigmento-4fa57.firebasestorage.app',
    iosBundleId: 'com.example.pigmento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRWRDYEVXovVqFoKtNy3k9e9nuuRMkkAM',
    appId: '1:189818621892:web:7ba121306cc74e0a0a9e91',
    messagingSenderId: '189818621892',
    projectId: 'pigmento-4fa57',
    authDomain: 'pigmento-4fa57.firebaseapp.com',
    storageBucket: 'pigmento-4fa57.firebasestorage.app',
    measurementId: 'G-4E14BP3BH5',
  );
}
